server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: test-drive-booking-bot
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:testdrive_booking_bot}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:postgres}}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: booking-hikari
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  jackson:
    time-zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    io.mitrofanovbp.testdrivebot: INFO
  file:
    name: ${LOG_FILE:}
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSX,UTC} %-5level [%thread] %logger{36} - %msg%n"

app:
  telegram-bot-token: ${APP_TELEGRAM_BOT_TOKEN:}
  telegram-bot-username: ${APP_TELEGRAM_BOT_USERNAME:test_drive_booking_bot}
  admin-token: ${APP_ADMIN_TOKEN:change-me}
